import{i as a,S as m}from"./assets/vendor-8c59ed88.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const l=document.querySelector(".loader");function f(){l.style.display="flex"}function p(){l.style.display="none"}function g(o){const r="44914505-36a6b847b314a6ef1bce975f7";return f(),fetch(`https://pixabay.com/api/?key=${r}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`).then(i=>{if(!i.ok)throw new Error("Failed to fetch images");return i.json()})}function y(o){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}const d=document.querySelector(".card-container");function b(o){const r=o.map(({webformatURL:s,largeImageURL:e,tags:t,likes:n,views:c,comments:u,downloads:h})=>`<li class="gallery-item">
            <a class="gallery-link" href="${e}">
                <img class="gallery-image" src="${s}" alt="${t}" width="360" height="200"/>
                <ul class="gallery-text-list">
                    <li class="gallery-text-item"><h3>Likes</h3><p>${n}</p></li>
                    <li class="gallery-text-item"><h3>Views</h3><p>${c}</p></li>
                    <li class="gallery-text-item"><h3>Comments</h3><p>${u}</p></li>
                    <li class="gallery-text-item"><h3>Downloads</h3><p>${h}</p></li>
                </ul>
            </a>
        </li>`).join("");d.innerHTML=r,new m(".card-container a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh()}const S=document.querySelector(".search-form");S.addEventListener("submit",x);function x(o){o.preventDefault();const r=o.currentTarget,i=r.elements.query.value.trim();i===""?a.error({title:"Error",message:"Please enter a search term!",position:"topRight"}):g(i).then(s=>{s.hits.length===0&&a.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),b(s.hits)}).catch(y).finally(()=>{r.reset(),p()})}
//# sourceMappingURL=commonHelpers.js.map
